/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista_Controlador;

import Modelo.IO.BBDD;
import Modelo.Usuario;
import java.awt.Color;
import java.util.regex.Pattern;
import javax.swing.BorderFactory;

/**
 *
 * @author DAM2_05
 */
public class CrearUsuario extends javax.swing.JFrame {

    /**
     * Creates new form CrearUsuario
     */
    private String usuario;
    private String correoRegex = "^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$";

    public CrearUsuario() {
        initComponents();
    }

    public CrearUsuario(String ventana) {

        initComponents();
        this.usuario = usuario;
        Texto_Password.setEchoChar('*');
        Texto_Password_Conf.setEchoChar('*');

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Info_Label = new javax.swing.JLabel();
        Texto_Usuario = new javax.swing.JTextField();
        Usuario_Label = new javax.swing.JLabel();
        Password_Label = new javax.swing.JLabel();
        Password_Conf_Label = new javax.swing.JLabel();
        Separador = new javax.swing.JSeparator();
        Info_Label_2 = new javax.swing.JLabel();
        Texto_Nombre = new javax.swing.JTextField();
        Texto_Correo = new javax.swing.JTextField();
        Texto_Apellidos = new javax.swing.JTextField();
        Nombre_Label = new javax.swing.JLabel();
        Apellidos_Label = new javax.swing.JLabel();
        Fecha_Nacimiento_Label = new javax.swing.JLabel();
        Correo_Label = new javax.swing.JLabel();
        Boton_Agregar = new javax.swing.JButton();
        Boton_Volver = new javax.swing.JButton();
        Texto_Password = new javax.swing.JPasswordField();
        Texto_Password_Conf = new javax.swing.JPasswordField();
        Fecha_Nacimiento = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agregar nuevo usuario");

        Info_Label.setText("Por favor, introduzca la información del nuevo usuario:");

        Usuario_Label.setText("Usuario");

        Password_Label.setText("Contraseña");

        Password_Conf_Label.setText("Confirmar contraseña");

        Info_Label_2.setText("Agregar datos opcionales del nuevo usuario:");

        Nombre_Label.setText("Nombre");

        Apellidos_Label.setText("Apellidos");

        Fecha_Nacimiento_Label.setText("Fecha nacimiento");

        Correo_Label.setText("Correo");

        Boton_Agregar.setText("Agregar");
        Boton_Agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Boton_AgregarMousePressed(evt);
            }
        });

        Boton_Volver.setText("Volver");
        Boton_Volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Boton_VolverMousePressed(evt);
            }
        });

        Fecha_Nacimiento.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(Info_Label_2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Info_Label)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(Password_Conf_Label)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Texto_Password_Conf, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Password_Label)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Texto_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Usuario_Label)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Texto_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 72, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Separador))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(Fecha_Nacimiento_Label)
                                            .addComponent(Correo_Label))
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Apellidos_Label)
                                            .addComponent(Nombre_Label))
                                        .addGap(44, 44, 44)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Texto_Nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                                    .addComponent(Texto_Correo)
                                    .addComponent(Texto_Apellidos)
                                    .addComponent(Fecha_Nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(Boton_Volver, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Boton_Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(70, 70, 70)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Info_Label)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Usuario_Label)
                    .addComponent(Texto_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Password_Label)
                    .addComponent(Texto_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(Password_Conf_Label)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Texto_Password_Conf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(Separador, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Info_Label_2)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Texto_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Nombre_Label))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Texto_Apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Apellidos_Label))
                        .addGap(32, 32, 32)
                        .addComponent(Fecha_Nacimiento_Label))
                    .addComponent(Fecha_Nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Texto_Correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Correo_Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Boton_Agregar)
                    .addComponent(Boton_Volver))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_AgregarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_AgregarMousePressed
        if (validaciones()) {
            BBDD.insertarUsuario(new Usuario(Texto_Usuario.getText(), String.valueOf(Texto_Password.getPassword()), Texto_Nombre.getText(), Fecha_Nacimiento.getDateFormatString(), Texto_Apellidos.getText(), Texto_Correo.getText()));
        }

//String nombre_usuario, String password, String nombre, String fecha_nacimiento, String apellidos, String correo
    }//GEN-LAST:event_Boton_AgregarMousePressed

    private void Boton_VolverMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_VolverMousePressed
        if (usuario == null) {
            this.dispose();
            new login().setVisible(true);
            return;
        }

        new Usuario_Logueado(usuario).setVisible(true);

    }//GEN-LAST:event_Boton_VolverMousePressed

    /**
     * @param args the command line arguments
     */
    public void vibrarPantalla() {
        final int originalX = this.getLocationOnScreen().x;  // Obtener la posiciï¿½n original en X
        final int originalY = this.getLocationOnScreen().y;  // Obtener la posiciï¿½n original en Y

        // Creamos un hilo para que no bloquee el hilo principal de la UI
        new Thread(() -> {
            try {
                for (int i = 0; i < 10; i++) {
                    // Mover la ventana a posiciones levemente distintas
                    this.setLocation(originalX + (int) (Math.random() * 10 - 5),
                            originalY + (int) (Math.random() * 10 - 5));
                    Thread.sleep(20);  // Pausa breve entre cada movimiento
                }
                // Volver a la posiciï¿½n original al finalizar
                this.setLocation(originalX, originalY);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }).start();
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearUsuario().setVisible(true);
            }
        });
    }

    public boolean validaciones() {
        for (Usuario usuario : Usuario.getUsuarios()) {
            if (usuario.getNombre().equalsIgnoreCase(Texto_Nombre.getText())) {
                Texto_Nombre.setBorder(BorderFactory.createLineBorder(Color.RED, 2));
                vibrarPantalla();
                return false;
            }
        }

        if (!String.valueOf(Texto_Password.getPassword()).equals(String.valueOf(Texto_Password_Conf.getPassword()))) {
            Texto_Password.setBorder(BorderFactory.createLineBorder(Color.RED, 2));
            Texto_Password_Conf.setBorder(BorderFactory.createLineBorder(Color.RED, 2));
            vibrarPantalla();
            return false;
        }

        if (Texto_Apellidos.getText().isBlank()) {
            Texto_Apellidos.setBorder(BorderFactory.createLineBorder(Color.RED, 2));
            vibrarPantalla();
            return false;
        }

        if (Fecha_Nacimiento.getDateFormatString().isBlank()) {
            Fecha_Nacimiento.setBorder(BorderFactory.createLineBorder(Color.RED, 2));
            vibrarPantalla();
            return false;
        }

        if (Texto_Nombre.getText().isBlank()) {
            Texto_Nombre.setBorder(BorderFactory.createLineBorder(Color.RED, 2));
            vibrarPantalla();
            return false;
        }

        if (Texto_Correo.getText().isBlank()) {
            Texto_Correo.setBorder(BorderFactory.createLineBorder(Color.RED, 2));
            vibrarPantalla();
            return false;
        }

        if (!Fecha_Nacimiento.getDateFormatString().matches("\\d{2} [A-Za-z]{3} \\d{4}")) {
            vibrarPantalla();
            Fecha_Nacimiento.setBorder(BorderFactory.createLineBorder(Color.RED, 2));
            return false;
        }

        if (!Pattern.matches(correoRegex, Texto_Correo.getText())) {
            vibrarPantalla();
            Texto_Correo.setBorder(BorderFactory.createLineBorder(Color.RED, 2));
            return false;
        }
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Apellidos_Label;
    private javax.swing.JButton Boton_Agregar;
    private javax.swing.JButton Boton_Volver;
    private javax.swing.JLabel Correo_Label;
    private com.toedter.calendar.JDateChooser Fecha_Nacimiento;
    private javax.swing.JLabel Fecha_Nacimiento_Label;
    private javax.swing.JLabel Info_Label;
    private javax.swing.JLabel Info_Label_2;
    private javax.swing.JLabel Nombre_Label;
    private javax.swing.JLabel Password_Conf_Label;
    private javax.swing.JLabel Password_Label;
    private javax.swing.JSeparator Separador;
    private javax.swing.JTextField Texto_Apellidos;
    private javax.swing.JTextField Texto_Correo;
    private javax.swing.JTextField Texto_Nombre;
    private javax.swing.JPasswordField Texto_Password;
    private javax.swing.JPasswordField Texto_Password_Conf;
    private javax.swing.JTextField Texto_Usuario;
    private javax.swing.JLabel Usuario_Label;
    // End of variables declaration//GEN-END:variables

}
