/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista_Controlador;

import Modelo.Usuario;

/**
 *
 * @author DAM2_05
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Usuario
     */

    String usuario;
    public Principal() {
        initComponents();
    }

    public Principal(String usr) {
        initComponents();
        usuario = usr;
        Texto_Bienvenida.setText("El usuario "+ usr + " está logueado");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        Bienvenido = new javax.swing.JLabel();
        Texto_Bienvenida = new javax.swing.JLabel();
        Cerrar_Sesion = new javax.swing.JButton();
        Imagen = new javax.swing.JLabel();
        Cambiar_Contraseña = new javax.swing.JButton();
        Crear_Usuario = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Principal");

        Bienvenido.setText("BIENVENID@");

        Texto_Bienvenida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        Cerrar_Sesion.setText("Cerrar Sesion");
        Cerrar_Sesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Cerrar_SesionMouseReleased(evt);
            }
        });

        Imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/image-removebg-preview.png"))); // NOI18N

        Cambiar_Contraseña.setText("Cambiar Contraseña");
        Cambiar_Contraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Cambiar_ContraseñaMousePressed(evt);
            }
        });

        Crear_Usuario.setText("Crear Usuario");
        Crear_Usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Crear_UsuarioMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(Imagen))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(Bienvenido))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Cerrar_Sesion, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(339, 339, 339)
                                .addComponent(Texto_Bienvenida))
                            .addComponent(Cambiar_Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Crear_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(167, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(Bienvenido)
                .addGap(18, 18, 18)
                .addComponent(Imagen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Texto_Bienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Crear_Usuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Cambiar_Contraseña)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(Cerrar_Sesion)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Cerrar_SesionMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Cerrar_SesionMouseReleased
        this.setVisible(false);
        new login().setVisible(true);
    }//GEN-LAST:event_Cerrar_SesionMouseReleased

    private void Cambiar_ContraseñaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Cambiar_ContraseñaMousePressed
        this.setVisible(false);
        new CambioContraseña().setVisible(true);
    }//GEN-LAST:event_Cambiar_ContraseñaMousePressed

    private void Crear_UsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Crear_UsuarioMousePressed
        this.setVisible(false);
        new CrearUsuario(usuario).setVisible(true);
    }//GEN-LAST:event_Crear_UsuarioMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bienvenido;
    private javax.swing.JButton Cambiar_Contraseña;
    private javax.swing.JButton Cerrar_Sesion;
    private javax.swing.JButton Crear_Usuario;
    private javax.swing.JLabel Imagen;
    private javax.swing.JLabel Texto_Bienvenida;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
